import type { Metadata } from "next";
import { Nunito, Nunito_Sans, Poppins } from "next/font/google";
import "./globals.css";
// import { UserProvider } from "@/contexts/UserContext";
import { Toaster } from "@/components/ui/toaster";
import {
  ClerkProvider,
} from "@clerk/nextjs";

const poppins = Poppins({
  weight: ["400", "700", "500", "600", "800", "300"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});
const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${nunito.variable} ${nunitoSans.variable} ${poppins.variable} antialiased`}
        >
          {/* <UserProvider> */}
          {children}
          {/* </UserProvider> */}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
